const chapterItems = [
  {
    chapterId: 1,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/hello-lesson.webp",
    mainText: "الترحيب بالاخرين",
    subText: "تعلم التحية عند مقابلة الأشخاص",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 1,
    lessonId: 2,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/introduce-lesson.webp",
    mainText: "تقديم نفسك",
    subText: "قل اسمك",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 1,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/wave.webp",
    mainText: "توديع الغير",
    subText: "كيف تودع الاخرين",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 1,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/coffeeshop.webp",
    mainText: "طلب القهوة",
    subText: "اطلب قهوتك ببساطة",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 1,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/checkpoint.webp",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 2,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/new-job.webp",
    mainText: "بدء وظيفة جديدة",
    subText: "البدايات الوظيفية اسهل معنا",
    url: "lesson/lesson",
    set: "set6",
  },
  {
    chapterId: 2,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/describe.webp",
    mainText: "وصف شخص",
    subText: "تحدث عن صفات الشخص",
    url: "lesson/lesson",
    set: "set7",
  },
  {
    chapterId: 2,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/new-home.webp",
    mainText: "منزل جديد",
    subText: "الانتقال الى منزل مختلف",
    url: "lesson/lesson",
    set: "set8",
  },
  {
    chapterId: 2,
    lessonId: 4,
    completed: false,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/outfits.webp",
    mainText: "جرب الملابس",
    subText: "اختبار زي جديد لنفسك",
    url: "lesson/lesson",
    set: "set9",
  },
  {
    chapterId: 2,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/checkpoint.webp",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set10",
  },
  {
    chapterId: 3,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "ربط المعلومات",
    subText: "بناء جمل أطول باللغة الانجليزي 'and, or , but'",
    url: "lesson/lesson",
    set: "set11",
  },
  {
    chapterId: 3,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "افعال النفي البسيط",
    subText: "صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set12",
  },
  {
    chapterId: 3,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "التحدث بعدة لغات",
    subText: "القدرة على التحدث بعدة لغاتك",
    url: "lesson/lesson",
    set: "set13",
  },
  {
    chapterId: 3,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "أشكال الفعل المنفية",
    subText: "كون صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set14",
  },
  {
    chapterId: 3,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/checkpoint.webp",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set15",
  },
  {
    chapterId: 4,
    lessonId: 1,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/PrepositionsOfPlace.jpg",
    mainText: "فهم حروف الجر للمكان",
    subText: "تعلّم كيفية وصف موقع الأشياء باستخدام حروف الجر الشائعة.",
    url: "lesson/lesson",
    set: "set16",
  },
  {
    chapterId: 4,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/city-info.jpg",
    mainText: "استكشاف معلومات عن المدينة",
    subText: "احصل على رؤى حول تخطيطات المدن والمواقع.",
    url: "lesson/lesson",
    set: "set17",
  },
  {
    chapterId: 4,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/traits-banner.jpg",
    mainText: "صفات الشخصية والسمات",
    subText: "تعلم وصف الشخصيات والسمات الشخصية",
    url: "lesson/lesson",
    set: "set18",
  },
  {
    chapterId: 4,
    lessonId: 4,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/gandparent-banner.jpg",
    mainText: "الأجداد والعائلة",
    subText: "تعلم مفردات حول الأجداد والعلاقات العائلية",
    url: "lesson/lesson",
    set: "set19",
  },
  {
    chapterId: 4,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/checkpoint.jpg",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set20",
  },
  {
    chapterId: 5,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/major-events.jpg",
    mainText: "أحداث الحياة وتجارب شخصية",
    subText: "تعلم مفردات حول الإنجازات والتجارب الحياتية",
    url: "lesson/lesson",
    set: "set21",
  },
  {
    chapterId: 5,
    lessonId: 2,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/graduation-banner.jpg",
    mainText: "إنجازات وتغيرات في الحياة",
    subText: "تعلم مفردات حول الترقيات'",
    url: "lesson/lesson",
    set: "set22",
  },
  {
    chapterId: 5,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/meet-banner.jpg",
    mainText: "المقابلات والتجمعات",
    subText: "تعلم مفردات حول المقابلات والأماكن الاجتماعية",
    url: "lesson/lesson",
    set: "set23",
  },
  {
    chapterId: 5,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/habit-banner.jpg",
    mainText: "الأنشطة والعادات اليومية",
    subText: "تعلم مفردات حول الروتين اليومي والأنشطة",
    url: "lesson/lesson",
    set: "set24",
  },
  {
    chapterId: 5,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/checkpoint.jpg",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set25",
  },
  {
    chapterId: 6,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/negative-events.jpg",
    mainText: "العادات السلبية",
    subText: "تعلم مفردات حول التصرفات غير المرغوبة باللغة الإنجليزية",
    url: "lesson/lesson",
    set: "set26",
  },
  {
    chapterId: 6,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الاجازات",
    subText: "الذهاب لاجازة عيد",
    url: "lesson/lesson",
    set: "set27",
  },
  {
    chapterId: 6,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الحصول على خطة هاتف",
    subText: "تعلم المفردات للحديث عن خطط الهاتف",
    url: "lesson/lesson",
    set: "set28",
  },
  {
    chapterId: 6,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "شرح ما تحتاجه",
    subText: "استمع إلى عميلة تشرح ما تحتاجه",
    url: "lesson/lesson",
    set: "set29",
  },
  {
    chapterId: 6,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set30",
  },
  {
    chapterId: 7,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الانتقال لبلد جديد",
    subText: "التعامل مع الحياة في بلد جديد",
    url: "lesson/lesson",
    set: "set31",
  },
  {
    chapterId: 7,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set32",
  },
  {
    chapterId: 7,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set33",
  },
  {
    chapterId: 7,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set34",
  },
  {
    chapterId: 7,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set35",
  },

  // ... (other lessons in Chapter 7)
  {
    chapterId: 8,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set36",
  },
  {
    chapterId: 8,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set37",
  },
  {
    chapterId: 8,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set38",
  },
  {
    chapterId: 8,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set39",
  },
  {
    chapterId: 8,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set40",
  },
  // ... (other lessons in Chapter 8)

  // Add more chapters for Advanced C1 (Chapters 9 and 10)
  {
    chapterId: 9,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set41",
  },
  {
    chapterId: 9,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set42",
  },
  {
    chapterId: 9,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set43",
  },
  {
    chapterId: 9,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set44",
  },
  {
    chapterId: 9,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set45",
  },

  // ... (other lessons in Chapter 9)
  {
    chapterId: 10,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set46",
  },
  {
    chapterId: 10,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set47",
  },
  {
    chapterId: 10,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set48",
  },
  {
    chapterId: 10,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set49",
  },
  {
    chapterId: 10,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set50",
  },
  {
    chapterId: 11,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "موضوعات متقدمة في الكتابة",
    subText: "تعلم الكتابة المتقدمة في اللغة",
    url: "lesson/lesson",
    set: "set51",
  },
  {
    chapterId: 11,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "موضوعات متقدمة في الكتابة",
    subText: "تعلم الكتابة المتقدمة في اللغة",
    url: "lesson/lesson",
    set: "set52",
  },
  {
    chapterId: 11,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "موضوعات متقدمة في الكتابة",
    subText: "تعلم الكتابة المتقدمة في اللغة",
    url: "lesson/lesson",
    set: "set53",
  },
  {
    chapterId: 11,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "موضوعات متقدمة في الكتابة",
    subText: "تعلم الكتابة المتقدمة في اللغة",
    url: "lesson/lesson",
    set: "set54",
  },
  {
    chapterId: 11,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set55",
  },

  // Chapter 12
  {
    chapterId: 12,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "مهارات الاستماع المتقدمة",
    subText: "تطوير مهارات الاستماع لمستوى أعلى",
    url: "lesson/lesson",
    set: "set56",
  },
  {
    chapterId: 12,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "مهارات الاستماع المتقدمة",
    subText: "تطوير مهارات الاستماع لمستوى أعلى",
    url: "lesson/lesson",
    set: "set57",
  },
  {
    chapterId: 12,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "مهارات الاستماع المتقدمة",
    subText: "تطوير مهارات الاستماع لمستوى أعلى",
    url: "lesson/lesson",
    set: "set58",
  },
  {
    chapterId: 12,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "مهارات الاستماع المتقدمة",
    subText: "تطوير مهارات الاستماع لمستوى أعلى",
    url: "lesson/lesson",
    set: "set59",
  },
  {
    chapterId: 12,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set60",
  },

  // Chapter 13
  {
    chapterId: 13,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "مهارات القراءة المتقدمة",
    subText: "تطوير مهارات القراءة لمستوى أعلى",
    url: "lesson/lesson",
    set: "set61",
  },
  {
    chapterId: 13,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "مهارات القراءة المتقدمة",
    subText: "تطوير مهارات القراءة لمستوى أعلى",
    url: "lesson/lesson",
    set: "set62",
  },
  {
    chapterId: 13,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "مهارات القراءة المتقدمة",
    subText: "تطوير مهارات القراءة لمستوى أعلى",
    url: "lesson/lesson",
    set: "set63",
  },
  {
    chapterId: 13,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "مهارات القراءة المتقدمة",
    subText: "تطوير مهارات القراءة لمستوى أعلى",
    url: "lesson/lesson",
    set: "set64",
  },
  {
    chapterId: 13,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set65",
  },

  // Chapter 14
  {
    chapterId: 14,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "المفردات المتقدمة",
    subText: "تعلم مفردات متقدمة",
    url: "lesson/lesson",
    set: "set66",
  },
  {
    chapterId: 14,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "المفردات المتقدمة",
    subText: "تعلم مفردات متقدمة",
    url: "lesson/lesson",
    set: "set67",
  },
  {
    chapterId: 14,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "المفردات المتقدمة",
    subText: "تعلم مفردات متقدمة",
    url: "lesson/lesson",
    set: "set68",
  },
  {
    chapterId: 14,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "المفردات المتقدمة",
    subText: "تعلم مفردات متقدمة",
    url: "lesson/lesson",
    set: "set69",
  },
  {
    chapterId: 14,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set70",
  },

  // Chapter 15
  {
    chapterId: 15,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "القواعد النحوية المتقدمة",
    subText: "فهم وتطبيق القواعد النحوية المتقدمة",
    url: "lesson/lesson",
    set: "set71",
  },
  {
    chapterId: 15,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "القواعد النحوية المتقدمة",
    subText: "فهم وتطبيق القواعد النحوية المتقدمة",
    url: "lesson/lesson",
    set: "set72",
  },
  {
    chapterId: 15,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "القواعد النحوية المتقدمة",
    subText: "فهم وتطبيق القواعد النحوية المتقدمة",
    url: "lesson/lesson",
    set: "set73",
  },
  {
    chapterId: 15,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "القواعد النحوية المتقدمة",
    subText: "فهم وتطبيق القواعد النحوية المتقدمة",
    url: "lesson/lesson",
    set: "set74",
  },
  {
    chapterId: 15,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set75",
  },

  // Chapter 16
  {
    chapterId: 16,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الكتابة الاحترافية",
    subText: "تطوير مهارات الكتابة الاحترافية",
    url: "lesson/lesson",
    set: "set76",
  },
  {
    chapterId: 16,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الكتابة الاحترافية",
    subText: "تطوير مهارات الكتابة الاحترافية",
    url: "lesson/lesson",
    set: "set77",
  },
  {
    chapterId: 16,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الكتابة الاحترافية",
    subText: "تطوير مهارات الكتابة الاحترافية",
    url: "lesson/lesson",
    set: "set78",
  },
  {
    chapterId: 16,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "الكتابة الاحترافية",
    subText: "تطوير مهارات الكتابة الاحترافية",
    url: "lesson/lesson",
    set: "set79",
  },
  {
    chapterId: 16,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set80",
  },

  // Chapter 17
  {
    chapterId: 17,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التحليل النقدي",
    subText: "تطوير مهارات التحليل النقدي",
    url: "lesson/lesson",
    set: "set81",
  },
  {
    chapterId: 17,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "التحليل النقدي",
    subText: "تطوير مهارات التحليل النقدي",
    url: "lesson/lesson",
    set: "set82",
  },
  {
    chapterId: 17,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "التحليل النقدي",
    subText: "تطوير مهارات التحليل النقدي",
    url: "lesson/lesson",
    set: "set83",
  },
  {
    chapterId: 17,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "التحليل النقدي",
    subText: "تطوير مهارات التحليل النقدي",
    url: "lesson/lesson",
    set: "set84",
  },
  {
    chapterId: 17,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set85",
  },

  // Chapter 18
  {
    chapterId: 18,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "مهارات التواصل",
    subText: "تطوير مهارات التواصل الفعّال",
    url: "lesson/lesson",
    set: "set86",
  },
  {
    chapterId: 18,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "مهارات التواصل",
    subText: "تطوير مهارات التواصل الفعّال",
    url: "lesson/lesson",
    set: "set87",
  },
  {
    chapterId: 18,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "مهارات التواصل",
    subText: "تطوير مهارات التواصل الفعّال",
    url: "lesson/lesson",
    set: "set88",
  },
  {
    chapterId: 18,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "مهارات التواصل",
    subText: "تطوير مهارات التواصل الفعّال",
    url: "lesson/lesson",
    set: "set89",
  },
  {
    chapterId: 18,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set90",
  },

  // Chapter 19
  {
    chapterId: 19,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "العرض التقديمي",
    subText: "تعلم كيفية إعداد عرض تقديمي",
    url: "lesson/lesson",
    set: "set91",
  },
  {
    chapterId: 19,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "العرض التقديمي",
    subText: "تعلم كيفية إعداد عرض تقديمي",
    url: "lesson/lesson",
    set: "set92",
  },
  {
    chapterId: 19,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "العرض التقديمي",
    subText: "تعلم كيفية إعداد عرض تقديمي",
    url: "lesson/lesson",
    set: "set93",
  },
  {
    chapterId: 19,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "العرض التقديمي",
    subText: "تعلم كيفية إعداد عرض تقديمي",
    url: "lesson/lesson",
    set: "set94",
  },
  {
    chapterId: 19,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set95",
  },

  // Chapter 20
  {
    chapterId: 20,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الخطابات الرسمية",
    subText: "تطوير مهارات كتابة الخطابات الرسمية",
    url: "lesson/lesson",
    set: "set96",
  },
  {
    chapterId: 20,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "تطوير مهارات كتابة الخطابات الرسمية",
    url: "lesson/lesson",
    set: "set97",
  },
  {
    chapterId: 20,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الخطابات الرسمية",
    subText: "تطوير مهارات كتابة الخطابات الرسمية",
    url: "lesson/lesson",
    set: "set98",
  },
  {
    chapterId: 20,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "الخطابات الرسمية",
    subText: "تطوير مهارات كتابة الخطابات الرسمية",
    url: "lesson/lesson",
    set: "set99",
  },
  {
    chapterId: 20,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set100",
  },

  // Chapter 21
  {
    chapterId: 21,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "كتابة التقارير",
    subText: "تعلم كيفية كتابة التقارير بشكل فعّال",
    url: "lesson/lesson",
    set: "set101",
  },
  {
    chapterId: 21,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "كتابة التقارير",
    subText: "تعلم كيفية كتابة التقارير بشكل فعّال",
    url: "lesson/lesson",
    set: "set102",
  },
  {
    chapterId: 21,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "كتابة التقارير",
    subText: "تعلم كيفية كتابة التقارير بشكل فعّال",
    url: "lesson/lesson",
    set: "set103",
  },
  {
    chapterId: 21,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "كتابة التقارير",
    subText: "تعلم كيفية كتابة التقارير بشكل فعّال",
    url: "lesson/lesson",
    set: "set104",
  },
  {
    chapterId: 21,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set105",
  },

  // Chapter 22
  {
    chapterId: 22,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الاستماع الفعّال",
    subText: "تطوير مهارات الاستماع الفعّال",
    url: "lesson/lesson",
    set: "set106",
  },
  {
    chapterId: 22,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الاستماع الفعّال",
    subText: "تطوير مهارات الاستماع الفعّال",
    url: "lesson/lesson",
    set: "set107",
  },
  {
    chapterId: 22,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الاستماع الفعّال",
    subText: "تطوير مهارات الاستماع الفعّال",
    url: "lesson/lesson",
    set: "set108",
  },
  {
    chapterId: 22,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "الاستماع الفعّال",
    subText: "تطوير مهارات الاستماع الفعّال",
    url: "lesson/lesson",
    set: "set109",
  },
  {
    chapterId: 22,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set110",
  },

  // Chapter 23
  {
    chapterId: 23,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "المهارات الاجتماعية",
    subText: "تطوير المهارات الاجتماعية في البيئة المهنية",
    url: "lesson/lesson",
    set: "set111",
  },
  {
    chapterId: 23,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "المهارات الاجتماعية",
    subText: "تطوير المهارات الاجتماعية في البيئة المهنية",
    url: "lesson/lesson",
    set: "set112",
  },
  {
    chapterId: 23,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "المهارات الاجتماعية",
    subText: "تطوير المهارات الاجتماعية في البيئة المهنية",
    url: "lesson/lesson",
    set: "set113",
  },
  {
    chapterId: 23,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "المهارات الاجتماعية",
    subText: "تطوير المهارات الاجتماعية في البيئة المهنية",
    url: "lesson/lesson",
    set: "set114",
  },
  {
    chapterId: 23,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set115",
  },

  // Chapter 24
  {
    chapterId: 24,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التفاوض الفعّال",
    subText: "تعلم مهارات التفاوض الفعّال",
    url: "lesson/lesson",
    set: "set116",
  },
  {
    chapterId: 24,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "التفاوض الفعّال",
    subText: "تعلم مهارات التفاوض الفعّال",
    url: "lesson/lesson",
    set: "set117",
  },
  {
    chapterId: 24,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "التفاوض الفعّال",
    subText: "تعلم مهارات التفاوض الفعّال",
    url: "lesson/lesson",
    set: "set118",
  },
  {
    chapterId: 24,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "التفاوض الفعّال",
    subText: "تعلم مهارات التفاوض الفعّال",
    url: "lesson/lesson",
    set: "set119",
  },
  {
    chapterId: 24,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set120",
  },

  // Chapter 25
  {
    chapterId: 25,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "القيادة والتأثير",
    subText: "تعلم مهارات القيادة والتأثير",
    url: "lesson/lesson",
    set: "set121",
  },
  {
    chapterId: 25,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "القيادة والتأثير",
    subText: "تعلم مهارات القيادة والتأثير",
    url: "lesson/lesson",
    set: "set122",
  },
  {
    chapterId: 25,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "القيادة والتأثير",
    subText: "تعلم مهارات القيادة والتأثير",
    url: "lesson/lesson",
    set: "set123",
  },
  {
    chapterId: 25,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "القيادة والتأثير",
    subText: "تعلم مهارات القيادة والتأثير",
    url: "lesson/lesson",
    set: "set124",
  },
  {
    chapterId: 25,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set125",
  },
];

export default chapterItems;
